#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /{_locale}
  controller: App\LHarm\RegistrationAppBundle\Controller\FrontendController::index

guest_form:
  path: /{_locale}/guest/
  controller: App\LHarm\RegistrationAppBundle\Controller\FrontendController::guestForm

check_in:
  path: /{_locale}/guest/checkin/
  controller: App\LHarm\RegistrationAppBundle\Controller\FrontendController::checkIn

check_out:
  path: /{_locale}/guest/checkout/
  controller: App\LHarm\RegistrationAppBundle\Controller\FrontendController::checkOut





